name: Upload Jar-Libraries
on: workflow_dispatch
jobs:
  build:
    name: assemble Libraries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    
    - name: Running gradle assembleRelease
      run: gradle assembleDebug

    - name: Uploading Jar Libraries
      uses: actions/upload-artifact@v2
      with:
        name: Jar-Libraries
        path: |
           subprojects
           terminal-view
           virtual-process
    
